name: Build Rust Executable

# Triggered on push and pull_request events (to the main branch).
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build the executable
        run: cargo build --release
      
      - name: Copy resources folder
        run: |
            mkdir -p target/release/resources
            xcopy "resources" "target/release/resources" /e /i

      - name: Upload the executable and resources
        uses: actions/upload-artifact@v4
        with:
          name: rust-exe-and-resources
          path: |
            target/release/*.exe
            target/release/resources
